-- table partitioning
-- list part

CREATE TABLE list_part
(
cusid NUMBER,
cusname VARCHAR2(20),
cuscountr VARCHAR2(20),
cussala NUMBER(10)
)
PARTITION BY LIST(cuscountr)
(
PARTITION p10 VALUES('india'),
PARTITION p11 VALUES('china'),
PARTITION p12 VALUES('rome'),
PARTITION p_default VALUES(DEFAULT)
);
--RANGE PARTITION

CREATE TABLE RANGE_part
(
cusid NUMBER,
cusname VARCHAR2(20),
cuscountr VARCHAR2(20),
cussala NUMBER(10)
)
PARTITION BY RANGE(cussala)
INTERVAL (5000)
(
PARTITION p1 VALUES LESS THAN 10000 ,
PARTITION p2 VALUES LESS THAN 20000 ,
PARTITION p3 VALUES LESS THAN 30000 ,
PARTITION p_other MAXVALUE
);


SELECT * FROM user_tab_partition;


CREATE TABLE RANGE_part
(
cusid NUMBER,
cusname VARCHAR2(20),
cuscountr VARCHAR2(20),
cussala NUMBER(10)
)
PARTITION BY RANGE(cussala)
INTERVAL (5000)
(
PARTITION p1 VALUES LESS THAN 10000 ,
PARTITION p2 VALUES LESS THAN 20000 ,
PARTITION p3 VALUES LESS THAN 30000 ,
PARTITION p_other MAXVALUE
);


CREATE TABLE RANGE_part
(
cusid NUMBER,
cusname VARCHAR2(20),
cuscountr VARCHAR2(20),
cussala NUMBER(10)
)
PARTITION BY RANGE HASH
PARTITIONS 3
STORE IN ('USERS,'TBS_1','SYSAUX');



